name: Node.js Package

on:
  push:
    branches:
    - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
